/**
 * English Strings
 * @format
 */

export const en = {
  auth: {
    email_or_phone: 'Email / Phone',
    password: 'Password',
    forgot_password: 'Forgot Password?',
    login: 'Login',
    loginWithOtp: 'Login with OTP',
    not_have_account: "Don't have an account?",
    register: 'Register',
    name: 'Name',
    email: 'Email',
    phone: 'Phone Number',
    confirm_password: 'Confirm Password',
    i_agree_to: 'I agree to the',
    terms_and_conditions: 'Terms and Conditions',
    signup: 'Sign Up',
    already_have_account: 'Already registered?',
    reset_password_will_send:
      'A reset password link will be send to entered email id',
    login_with_phone_caption:
      'A verification code will be send to entered phone number',
    verification_sent_caption:
      'A verification code has been sent to your phone number',
    submit: 'Submit',
    not_receive: 'Didn’t Receive code?',
    resend_otp: 'You can resend OTP in',
    resend: 'Resend SMS',
  },
  profile: {
    change_password: 'Change Password',
    add_edit_address: 'Add/Edit Address',
    terms_and_condition: 'Terms & Conditions',
    logout: 'Logout',
    mobile_no: 'Mobile number',
    old_password: 'Old Password',
    new_password: 'New Password',
    confirm_password: 'Confirm Password',
    submit: 'Submit',
    name: 'Name',
    email: 'Email',
    phone: 'Phone Number',
  },
  search_product: 'Search Product',
  what_are_you_searching: 'What are you searching for ?',
  type_product_name: 'Type product name or category to get matching results',
  browse_category: 'Browse Categories',
  view_all: 'View All',
  add_to_card: 'Add to cart',
  out_of_stock: 'Out Of Stock',
  quick_overview: 'Quick Overview',
  loading_details: 'Getting Details',
  save: 'Save',
  my_basket: 'My Basket',
  items: 'items',
  payment_detail: 'Payment Detail',
  mrp_total: 'MRP Total',
  product_discount: 'Product Discount',
  total_amount: 'Total Amount',
  delivery_charge: 'Delivery Charge',
  you_save: 'You Save',
  payable_amount: 'Payable Amount',
  place_order: 'Place Order',
  submit_order: 'Submit Order',
  qty: 'Qty',
  select_delivery_address: 'Select Delivery Address',
  add_address: 'Add Address',
  change: 'Change',
  edit: 'Edit',
  deliver_here: 'Deliver Here',
  order_date: 'Order Date',
  order_items: 'Order Items',
  order_status: 'Order Status',
  view_details: 'View Details',
  order_summary: 'Order Summary',
  payment_mode: 'Payment Mode',
  items_in_order: 'Items in this order',
  orderId: 'Order id',
  delivered: 'Delivered',
  delivery_address: 'Delivery Address',
  coupon_for_you: 'Promos for you',
  apply: 'Apply',
  applied: 'Applied',
  applied_Coupon: 'Applied Coupon',
  coupon_discount: 'Coupon discount',
  choose_a_color: 'Choose a Color',
  choose_a_size: 'Choose a Size',
  not_available: 'Not available',
  done: 'Done',
  continue_shopping: 'Continue Shopping',
  view_status: 'View Status',

  address: {
    name: 'Name *',
    phone: 'Phone *',
    pin_code: 'Pin Code *',
    house_flat_no: 'Flat/House Number',
    society: 'Society',
    area_sector: 'Area / Sector *',
    land_mark: 'Landmark *',
    city: 'City *',
    state: 'State *',
    save_address: 'Save Address',
  },

  common: {
    ok: 'Ok',
    rupee: '₹',
    select_option: 'Select Option',
    take_photo: 'Take Photo',
    choose_from_gallery: 'Choose From Gallery',
    cancel: 'Cancel',
    open_setting: 'Open Setting',
    left: '',
    appName: 'Grocer21',
    headline: 'Shop smart, Shop easy!',
  },
  permission: {
    blocked_camera_title: 'Camera Access Blocked',
    blocked_camera_message:
      'We cannot access your camera due to camera permission is blocked, please enable camera permission from setting.',
    blocked_photo_title: 'Photo Access Blocked',
    blocked_photo_message:
      'We cannot access your photo gallery due to photo library permission is blocked, please enable photo library permission from setting.',
  },

  // Header titles
  header: {
    login: 'Login',
    verification: 'Verification',
    register: 'Register',
    forgot_password: 'Forgot Password',
    my_cart: 'My Cart',
    add_address: 'Add Address',
    update_address: 'Update Address',
    my_address: 'My Address',
    my_order: 'My Order',
    order_detail: 'Order Detail',
    categories: 'Categories',
    my_profile: 'My Profile',
    change_password: 'Change Password',
    update_profile: 'Update Profile',
  },
  drawer: {
    home: 'Home',
    browse_categories: 'Browse Categories',
    my_order: 'My Order',
    my_profile: 'My Profile',
    search_product: 'Search Product',
    logout: 'Logout',
  },
  tabs: {
    home: 'Home',
    categories: 'Categories',
    order: 'Order',
    profile: 'Profile',
    help: 'Help',
  },

  // Errors
  validation: {
    email_or_phone_required: 'Email or phone number is required',
    email_required: 'Email is required',
    email_invalid: 'Please enter a valid email address',
    password_required: 'Password is required',
    password_mismatch: 'Passwords must match',
    password_min: 'Password must be at least 5 character long',
    name_required: 'Name is required',
    phone_required: 'Phone number is required',
    phone_invalid: 'Please enter a valid phone number',
    accept_terms: 'Please accept terms and conditions',
    pin_code_required: 'Please enter your pin code',
    pin_code_invalid: 'Please enter a valid postal code',
    area_required: 'Please enter your address',
    landmark_required: 'Please enter your landmark',
    city_required: 'Please select your city',
    state_required: 'Please select your state',
  },

  errors: {
    login_failed: 'Login Failed',
  },
  success: {
    password_reset_link_sent:
      'We have sent a link to your email address to reset your password',
    account_created: 'Account created successfully',
    profile_updated: 'Profile updated successfully',
    password_updated: 'Your password updated successfully',
  },
  // Loading messages
  loading: {
    login: 'Login...',
  },
  messages: {
    cart_item_added: '{{productName}} have been added to your cart.',
    cart_item_removed: '{{productName}} have been removed from cart.',
    address_added: 'New address have been added to your account',
    address_updated: 'Address updated successfully',
    order_placed: 'Order placed successfully',
    uploading_image: 'Uploading image...',
    coupon_applied: 'Coupon applied successfully',
    order_placed_caption:
      'Your order has been placed. You can view status of your order in My Order tab.',
  },
};
